### PR TITLE
Task 4 implementation

### PR DESCRIPTION
**Pull request by byslavik**
**COMPLETED TASKS:**
- db is created
- updated serverless file to deploy lambda
- get products and get product lambdas updated to return products from db
- added incoming data validation
- added 500 status for internal error
- added logging for each lambda function
- it is integrated with FE part

**LINKS:**

- Get products: GET https://zbw8eh1lt1.execute-api.eu-west-1.amazonaws.com/dev/products/
- GetProduct by Id: GET https://zbw8eh1lt1.execute-api.eu-west-1.amazonaws.com/dev/products/{productId}
- Add product: POST https://zbw8eh1lt1.execute-api.eu-west-1.amazonaws.com/dev/products/
- Request schema:
```typescript
 {
    title: string;
    brand_id: string;
    category_id: string;
    description: string;
    price: number;
    imgurl: string;
}
```
- Link to the working app: https://d1nr9q145u9jd4.cloudfront.net/
- Link to FE PR: https://github.com/byslavik/nodejs-aws-fe/pull/3

**TODOs:**
- adjust product add form
- add ability to manage brands and categories

**EVALUATION CRITERIA:**

Reviewers should verify the lambda functions by invoking them through provided URLs.

1 - Task 4.1 is implemented
3 - TASK 4.2 is implemented lambda links are provided and returns data
4 - TASK 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
5 - Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.
Additional (optional) tasks (but nice to have):

+1 - POST/products lambda functions returns error 400 status code if product data is invalid
+1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
+1 - All lambdas do console.log for each incoming requests and their arguments

### CODE REVIEW

**Comment by Julia-ivv** [comment]
GetProduct by Id doesn't work, can you fix it?
image

**Comment by ilya-moskovtsev** [comment]
> * Link to the working app: https://d1nr9q145u9jd4.cloudfront.net/

I couldn't add a new product via the front-end. https://d1nr9q145u9jd4.cloudfront.net/admin/product-form/

**Comment by byslavik** [comment]
> GetProduct by Id doesn't work, can you fix it?
> image

OOps, working on it

**Comment by byslavik** [comment]
> > * Link to the working app: https://d1nr9q145u9jd4.cloudfront.net/
> 
> I couldn't add a new product via the front-end. https://d1nr9q145u9jd4.cloudfront.net/admin/product-form/

yep, I have a TODO in PR description for that. Need to add extra fields and services for brands and categories. So plan to update it later. 

As alternative I can fix it right now, but without adding of brand and category. But I think this is out of scope of that ticket

**Comment by byslavik** [comment]
> GetProduct by Id doesn't work, can you fix it?
> image

Issue with getProductById has been fixed

**Comment by Julia-ivv** [comment]
> > GetProduct by Id doesn't work, can you fix it?
> > image
> 
> Issue with getProductById has been fixed

still doesn't work

image

**Comment by byslavik** [comment]
> > > GetProduct by Id doesn't work, can you fix it?
> > > image
> > 
> > 
> > Issue with getProductById has been fixed
> 
> still doesn't work
> 
> image

Yep. Figured out another issue with joining of tables. updated and now seems to be working

**Comment by byslavik** [comment]
Also removed categories and brands. Now it is able to add product with api

**Comment by ilya-moskovtsev** [comment]
> > > * Link to the working app: https://d1nr9q145u9jd4.cloudfront.net/
> > 
> > 
> > I couldn't add a new product via the front-end. https://d1nr9q145u9jd4.cloudfront.net/admin/product-form/
> 
> yep, I have a TODO in PR description for that. Need to add extra fields and services for brands and categories. So plan to update it later.
> 
> As alternative I can fix it right now, but without adding of brand and category. But I think this is out of scope of that ticket

I agree that new fields are out of the scope. I was able to add a product using the existing form.

**Pull request merged**
